#!/usr/bin/env python3

import pulsectl

pulse = pulsectl.Pulse('test')

sinks = []
default = pulse.server_info().default_sink_name

for i in pulse.sink_list():
    if("Game" in i.description):
        sinks.append(i)
    elif("Built-in" in i.description):
        sinks.append(i)

for i in sinks:
    if(default != i.name):
        pulse.default_set(i)
