#!/usr/bin/env python3

import pulsectl
import sys

pulse = pulsectl.Pulse('test')

sinks = sys.argv[1:]
default = pulse.server_info().default_sink_name
sink_list = []

for i in sinks:
    for j in pulse.sink_list():
        if(i in j.name):
            sink_list.append(j)
        elif(i in j.description):
            sink_list.append(j)

for i in range(len(sink_list)):
    if(default == sink_list[i].name):
        pulse.default_set(sink_list[(i + 1) % len(sink_list)])
        break
    elif(default not in sink_list):
        pulse.default_set(sink_list[0])
        break
