#!/usr/bin/env python3

import pulsectl
import sys

pulse = pulsectl.Pulse('test')
sinks = sys.argv[1:]

def all_sinks():
    sinks = pulse.sink_list()
    sinks_names = []
    for i in sinks:
        if(i.name != "OBS"): # Ignore virtual sink
            sinks_names.append(i.name)
    return sinks_names

if(len(sinks) < 1):
    sinks = all_sinks()
default = pulse.server_info().default_sink_name
sink_list = []
sinks_looped = 0
sink_changed = False

for i in sinks:
    for j in pulse.sink_list():
        if(i in j.name):
            sink_list.append(j)
        elif(i in j.description):
            sink_list.append(j)

for i in range(len(sink_list)):
    if(default == sink_list[i].name):
        pulse.default_set(sink_list[(i + 1) % len(sink_list)])
        sink_changed = True
        break
    elif(default != sink_list[i].name):
        sinks_looped += 1
    if(sinks_looped == len(sink_list) and not sink_changed):
        pulse.default_set(sink_list[0])
        break
