#!/usr/bin/env python
from __future__ import unicode_literals
import youtube_dl
import argparse

parser = argparse.ArgumentParser(description="Download videos from crunchyroll.com")
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument("-f", "--file", type=str, dest="file", help="Specify a file with links to download, one url per line")
group.add_argument("-u", "--url", type=str, dest="url", help="Specify a url to download")
parser.add_argument("-s", type=str, dest="subs", help="Specify language for subs to use")
parser.add_argument("--list-subs", action="store_true", dest="list_subs", help="Specify if only list available subs for link")
parser.add_argument("--simulate", action="store_true", dest="simulate", help="Simulate download")
args = parser.parse_args()

links = []
subs = []
quiet = True
simulate = False
list_subs = False

if(args.subs):
    if(len(args.subs) > 0):
        subs = args.subs.replace(" ", ",").replace(",,", ",").split(",")

if(args.file):
    links = list(filter(None, open(args.file, "r").read().split("\n")))
elif(args.url):
    links.append(args.url)

if(args.list_subs):
    quite = False
    simulate = True
    list_subs = True
elif(args.simulate):
    simulate = True

ydl_opts = {
    'format': 'bestvideo[height<=720][ext=mp4]+bestaudio/best[height<=720][ext=mp4]',
    'outtmpl': '~/Nextcloud/Video/Series/%(series)s/Season_01/%(series)s_S01E%(episode_number)02d.%(ext)s',
    'writesubtitles': True,
    'subtitleslangs': subs,
    'nooverwrites': True,
    'quiet':  quiet,
    'no_warnings': True,
    'listsubtitles': list_subs,
    'simulate': simulate,
    'forcetitle': True,
    'forcefilename': True,
    'restrictfilenames': True,
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(links)
