#!/usr/bin/env python
from __future__ import unicode_literals
import youtube_dl
import argparse

parser = argparse.ArgumentParser(description="Download videos from crunchyroll.com")
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument("-f", "--file", type=str, dest="file", help="Specify a file with links to download, one url per line")
group.add_argument("-u", "--url", type=str, dest="url", help="Specify a url to download")
parser.add_argument("-s", type=str, dest="subs", help="Specify language for subs to use")
parser.add_argument("--list-subs", action="store_true", dest="list_subs", help="Specify if only list available subs for link")
parser.add_argument("--simulate", action="store_true", dest="simulate", help="Simulate download")
# parser.add_argument("--no-directory", action="store_true", dest="no_dir", help="Save file in current directory, dont create subdirectory for Serie and season to put files in")
parser.add_argument("-S", "--season", type=str, dest="season", help="Specify the season")
parser.add_argument("-y", type=int, dest="year", help="Specify the year the series started")
args = parser.parse_args()

links = []
subs = []
quiet = True
simulate = False
list_subs = False
season = ""
year = ""

if(args.subs):
    if(len(args.subs) > 0):
        subs = args.subs.replace(" ", ",").replace(",,", ",").split(",")

if(args.file):
    links = list(filter(None, open(args.file, "r").read().split("\n")))
elif(args.url):
    links.append(args.url)

if(args.list_subs):
    quiet = False
    list_subs = True
elif(args.simulate):
    simulate = True
    quiet = False

if(args.season):
    if(len(args.season) < 2):
        season = "0"
        season += args.season
    elif(args.season.lower() == "special"):
        season = "00"
    elif(len(args.season) >= 2):
        season = args.season
elif(not args.season and args.url):
    season = "01"
elif(not args.season and args.file):
    season = "%(season_number)02d"

if(args.year):
    year = "(" + str(args.year) + ")"

if(args.url):
    file_output = "%(series)s_S" + season + "E%(episode_number)02d.%(ext)s"
elif(args.file):
    file_output = "%(series)s" + year + "/Season_" + season + "/%(series)s_S" + season + "E%(episode_number)02d.%(ext)s"

ydl_opts = {
    'format': 'bestvideo[height<=720][ext=mp4]+bestaudio/best[height<=720][ext=mp4]',
    'outtmpl': file_output,
    'writesubtitles': True,
    'subtitleslangs': subs,
    'nooverwrites': True,
    'quiet':  quiet,
    'no_warnings': True,
    'listsubtitles': list_subs,
    'simulate': simulate,
    'forcetitle': True,
    'forcefilename': True,
    'restrictfilenames': True,
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(links)
