#!/bin/bash

if [ -z $1 ]; then
	stream=$(zenity --entry --text "Enter twitch stream name to open:" --title "Twitch")
	if [ -z $stream ]; then
		echo "Empty stream name"
	else
		streamlink https://twitch.tv/$stream
	fi
else
	streamlink https://twitch.tv/$1
fi
