#!/usr/bin/env python3

import json
import time
import psutil

def get_interfaces():
    interfaces = psutil.net_if_addrs()
    interface_json = dict()
    for i in interfaces.keys():
        if(i not in interface_json):
            interface_json[i] = dict()
        interface_json[i]['connection'] = "connected" if interfaces[i][0].family != psutil.AF_LINK else "disconnected"
        interface_json[i]['ip'] = interfaces[i][0].address if interfaces[i][0].family != psutil.AF_LINK else ""
        interface_json[i]['netmask'] = interfaces[i][0].netmask if interfaces[i][0].family != psutil.AF_LINK else ""
        interface_json[i]['broadcast'] = interfaces[i][0].broadcast if interfaces[i][0].family != psutil.AF_LINK else ""

    return interface_json

try:
    while(True):
        try:
            print(json.dumps(get_interfaces()), flush=True)
        except json.decoder.JSONDecodeError:
            print("{}", flush=True)
        time.sleep(10)
except KeyboardInterrupt:
    pass
